### PR TITLE
Backport some changes from Option

### PR DESCRIPTION
**Pull request by Lctrs**
Backporting https://github.com/prewk/option/pull/7, https://github.com/prewk/option/pull/8, and https://github.com/prewk/option/pull/11.

### CODE REVIEW

**Comment by Lctrs** [comment]
@prewk you can the result here : https://github.com/Lctrs/result/pull/1

**Comment by prewk** [comment]
Awesome work! I'll bump both after this merge, yes?

**Comment by Lctrs** [comment]
Yes please.

And thank you for these library. Wanted to do this myself before I found yours.

**Comment by prewk** [comment]
I'm just glad people use it!

I liked it so much in Rust I forced all my poor co-workers to use it in our pretty large codebase. Without Psalm (generics) it wasn't always that popular I must say haha.. Nowadays I don't code PHP anymore so it's fun to jump back sometimes.

Bumped both, thanks a lot for your contributions!

**Pull request merged**
