### PR TITLE
big refactor

### PR DESCRIPTION
**Pull request by Lctrs**
Same as https://github.com/prewk/option/pull/17

* dropping support for `PHP < 8.1.0`
* simplify phpdoc types, making `Result` the only source of truth for most methods
* Turning `Ok<T, E>` into `Ok<T>` and `Err<T,E>` into `Err<E>`
* added some static analysis assert for `Result#isOk()` and `Result#isErr()`
* added a bunch of missing methods on `Result` from their Rust counterparts
* migrating from phpspec to PHPUnit
* added a Makefile to help during development
* added a coding standard via `easy-coding-standard`
* added mutation testing coverage via `infection`
* added some static analysis tests
* modernize github actions setup
* added dependabot config
* upgrading all dependencies

### CODE REVIEW

**Comment by prewk** [comment]
Well done! This is more your lib than mine now.

**Comment by prewk** [comment]
I'm going to tag them 4.0.0.

I'm thinking about what to add as `Result`/`Option` dependency constraint in `composer.json`. Would it make sense to make them require each other's `4.0.0`?

**Comment by Lctrs** [comment]
If you're going with a new major, i have some additional BC i want to integrate before.

And yes, I think it would be better to make these changes in composer

**Comment by prewk** [comment]
Alright, I'll await your additional BC then until I tag. Let me know!

**Comment by calvinalkan** [comment]
Hey @prewk @Lctrs 

I want to share my thoughts, as I think I've pretty much experimented with every possible way of porting a Result type to PHP with type safety via Psalm.

The biggest PITA is that Psalm, there is no "enum like" template support.

Meaning, that any class extending this:

```php
/**
 * @template TOk
 * @template TErr
 */
class Result {
    
}


```

must always provide both paramters. 

This presents the following problem:

Suppose we have this function:

```php
function doStuff(): Result
{
    if (rand(0, 1) === 1) {
        return new Ok('Hello');
    }
    
    return new Err(new CustomErrorClass('World'));
}
```

We want every call site to be aware of the internal types. 

Meaning, this should pass psalm validation without any additonal checks:


```php
$result = doStuff();

if ($result->isOk()){
    echo strtolower($result->unwrap());
} else {
    echo $result->unwrapErr()->message;
}
```

Ofc, the current code throws a bunch of psalm errors, rightfully so. 

Ideally, this annotation would work:

```php
**
 * @return Result<string, CustomErrorClass>
 */
function doStuff(): Result
{
    if (rand(0, 1) === 1) {
        return new Ok('HELLO');
    }
    
    return new Err(new CustomErrorClass('ERROR'));
}
```

Which would resolve the issue at the call site.

But with the above annotation, the `doStuff` method itself is invalid because again, the Result class with two template parameters needs both templates! It's not an enum

image

Therefore, it seems like the only way to get both a) type safety at call site and b) valid return types inside the method is to do something like this:

```php
**
 * @return Ok<string>|Err<CustomErrorClass>
 */
function doStuff(): Result
{
    if (rand(0, 1) === 1) {
        return new Ok('HELLO');
    }
    
    return new Err(new CustomErrorClass('ERROR'));
}

```

Where both Ok and Err just take on template paramter. The Result class would be superfluous in this scenario.

And if you don't need all the `map` ànd_or` utilities, you simplify this to something like this:

```php
/**
 * @param mixed $result
 *
 * @psalm-assert-if-true Err $result
 */
function isErr($result): bool
{
    return $result instanceof Err;
}

/**
 * @return string|Err<CustomErrorClass>
 */
function doStuff(): string|Err
{
    if (rand(0, 1) === 1) {
        return 'OK';
    }
    
    return new Err(new CustomErrorClass('ERROR'));
}

$result = doStuff();

if(isErr($result)) {
    // Do stuff with error.
} else {
    // This is now a string.
    echo $result;
}
```

I'd love to somehow make this work like in Rust, but I think the fundamental blockade is that `Result<Ok,Err>` is not treated like an enum in psalm.

**Comment by Lctrs** [comment]
Hmmm weird, we do have a [static analysis test](https://github.com/prewk/result/blob/861f5defdf8d54b357d05ef48581685a47a01d2f/test/StaticAnalysis/narrow-ok-err.php#L33) that covers the `@return Result<string, CustomErrorClass>` part, I thought this would work.

**Comment by calvinalkan** [comment]
> Hmmm weird, we do have a [static analysis test](https://github.com/prewk/result/blob/861f5defdf8d54b357d05ef48581685a47a01d2f/test/StaticAnalysis/narrow-ok-err.php#L33) that covers the `@return Result<string, CustomErrorClass>` part, I thought this would work.

Thanks, I'll try and reproduce this test case. Maybe it's due to plsam versions.

**Comment by calvinalkan** [comment]
@Lctrs 

Results with the exact same psalm config and test file across different psalm version.

4.X.X

```
FILE: src/test.php

+----------+------+-------------------------+------------------------------------------------------------------------+
| SEVERITY | LINE | ISSUE                   | DESCRIPTION                                                            |
+----------+------+-------------------------+------------------------------------------------------------------------+
| ERROR    | 31   | MixedReturnTypeCoercion | The declared return type 'Prewk\Result<string, int>' for Prewk\Result\ |
|          |      |                         | Test\StaticAnalysis\testResultTypesCanBeComposedFromOkAndErrTypes is m |
|          |      |                         | ore specific than the inferred return type 'Prewk\Result\Err<mixed>|Pr |
|          |      |                         | ewk\Result\Ok<mixed>'                                                  |
| ERROR    | 36   | MixedReturnTypeCoercion | The type 'Prewk\Result\Err<mixed>' is more general than the declared r |
|          |      |                         | eturn type 'Prewk\Result<string, int>' for Prewk\Result\Test\StaticAna |
|          |      |                         | lysis\testResultTypesCanBeComposedFromOkAndErrTypes                    |
| ERROR    | 36   | InvalidArgument         | Argument 1 of Prewk\Result\Err::__construct expects Prewk\Result\E, bu |
|          |      |                         | t 1 provided                                                           |
| ERROR    | 39   | MixedReturnTypeCoercion | The type 'Prewk\Result\Ok<mixed>' is more general than the declared re |
|          |      |                         | turn type 'Prewk\Result<string, int>' for Prewk\Result\Test\StaticAnal |
|          |      |                         | ysis\testResultTypesCanBeComposedFromOkAndErrTypes                     |
| ERROR    | 39   | InvalidArgument         | Argument 1 of Prewk\Result\Ok::__construct expects Prewk\Result\T, but |
|          |      |                         |  'value' provided                                                      |
+----------+------+-------------------------+------------------------------------------------------------------------+
```

---

<5.5.0 (same)
 
 ---
 
 The error only goes away in release 5.5.0
 
```
 result-type-test# psalm --output-format=compact --no-cache && psalm --version
Target PHP version: 8.1 (inferred from current PHP version) Enabled extensions: .
Scanning files...
Analyzing files...

░
Psalm 5.5.0@b63061a27f2683ec0f3509012bb22daab3b65b61
```

**Comment by Lctrs** [comment]
Okay thanks for testing this. So the issue (if any) is not on our side then. We won't support every version possible for all existing static analysis tools. We'll only support the latest. It means you'll have to upgrade psalm or live with these errors in the baseline.

**Comment by calvinalkan** [comment]
I've opened this issue upstream to hopefully get some clarification of what the expected behavior is in psalm.

If this is a bug in psalm that makes it work, we'd probably not want to rely on that...?

https://github.com/vimeo/psalm/issues/10988

That said, if this is the correct behavior, you can actually modify the Ok and Err class to use never instead of mixed (see the example) which seems more accurate.

**Comment by Lctrs** [comment]
Yeah I thought about using `never`, but it makes psalm throwing some errors down the line, so I didn't dig it.

**Comment by calvinalkan** [comment]
Do you remember in what cases?

---

Also, just a heads-up:

https://github.com/prewk/result/blob/861f5defdf8d54b357d05ef48581685a47a01d2f/src/Result.php#L33

Double psalm-if-this annotation is not currently supported by psalm :/

https://github.com/vimeo/psalm/issues/10851

It only recognizes the first one and looses type information on the second one.

Until that's fixed, probably best to have the `Err/None` case the first one, since that will error if you try to unwrap a known Err/None.

**Comment by calvinalkan** [comment]
The main issue I see with using `never` is that you can't have any parameter on an Option that is of type T because you get:

``psalm: ReservedWord: Parameter cannot be never``

**Comment by Lctrs** [comment]
For Option, after turning `None<T>` into `None<never>`: 
```
ERROR: ReservedWord - src/Option.php:61:15 - Parameter cannot be never (see http
s://psalm.dev/095)
     * @param T $optb


ERROR: NoValue - src/Option/None.php:54:9 - All possible types for this return w
ere invalidated - This may be dead code (see https://psalm.dev/179)
        return $optb;


ERROR: NoValue - src/Option/None.php:59:9 - All possible types for this return w
ere invalidated - This may be dead code (see https://psalm.dev/179)
        return $op();
```

For Result, after turning into `Ok<T, never>` and `Err<never, E>`:
```
ERROR: MixedReturnTypeCoercion - src/Result/Err.php:52:27 - The declared return 
type 'Prewk\Option<never>' for Prewk\Result\Err::ok is more specific than the in
ferred return type 'Prewk\Option\None<mixed>' (see https://psalm.dev/197)
    public function ok(): Option


ERROR: MixedReturnTypeCoercion - src/Result/Err.php:54:16 - The type 'Prewk\Opti
on\None<mixed>' is more general than the declared return type 'Prewk\Option<neve
r>' for Prewk\Result\Err::ok (see https://psalm.dev/197)
        return new None();


ERROR: NoValue - src/Result/Err.php:157:9 - All possible types for this return w
ere invalidated - This may be dead code (see https://psalm.dev/179)
        return $optb;


ERROR: NoValue - src/Result/Err.php:162:9 - All possible types for this return w
ere invalidated - This may be dead code (see https://psalm.dev/179)
        return $op($this->err);


ERROR: InvalidArgument - test/Unit/ErrTest.php:286:58 - Argument 1 of Prewk\Resu
lt\Err::unwrapOr expects never, but 'default' provided (see https://psalm.dev/00
4)
        self::assertEquals($defaultValue, $err->unwrapOr($defaultValue));


ERROR: InvalidArgument - test/Unit/ErrTest.php:298:65 - Argument 1 of Prewk\Resu
lt\Err::unwrapOrElse expects callable('error'=):never, but pure-Closure():'new e
rror' provided (see https://psalm.dev/004)
        self::assertEquals($newErrorMessage, $err->unwrapOrElse(static fn () => 
$newErrorMessage));
```

I have removed errors related to dependencies on each other. We can probably fix all of these by tweaking the types but I haven't given a thought about it to be honest.

**Comment by calvinalkan** [comment]
I had an internal version of a Result/Option library (before I came across this), and the one thing that always seems to err is this one:

`ERROR: ReservedWord - src/Option.php:61:15 - Parameter cannot be never`

Or more broadly, if a "subclass" (None/Err) has `never` as `T`
, then each method on the "parent class" (Result/Option) will error on all methods that take `T` as a method parameter (`unwrap_or`, etc.)

All of this is probably solvable, but the biggest "worry" for me is that all this possibly relies on a bug/regression in psalm that might be reverted. 

Essentially, for as long as I have used psalm.

`Result<string,mixed> | Result<mixed,int>` was never the same as `Result<string,int>`

If that potential "bug" in Psalm gets reverted, you'd need to start type hinting every method explicit as a Union type of `OK<Tok>|Err<Terr>` (or loose type-safety).

**Comment by prewk** [comment]
I don't have anything to add here, but do you want me to bump it yet?

**Comment by calvinalkan** [comment]
> I don't have anything to add here, but do you want me to bump it yet?

Sure, a bump on upstream issue could be good.

**Comment by prewk** [comment]
I think it makes sense to bump as 4.0.0 and raise the Option lib requirement to `"prewk/option": ">= 4.0.0"` and vice versa in the Option lib. Will see if I find time for it tomorrow.

**Comment by prewk** [comment]
..OTOH, there's no real need for raising the requirement of the other (result/option depending on where you are) lib, because they do not rely on any new APIs. Basically only static analysis would suffer.

I'll keep the same requirements and just bump.

**Pull request merged**
